config/routes.rb
Lookatmepuma::Application.routes.draw do

    devise_for :users #, :controllers => { :registrations => 'registrations' }

    namespace :admin do
      root :to => 'disciplines#index'

      resources :disciplines, :only => [:index, :show, :destroy] do
        resources :votes, :only => [:index, :destroy]
        resources :photos, :only => [:create, :destroy]
        member do
          get :approve
          get :reject
        end
        collection do
          get :winners
          get :send_notification_to_winners
        end
      end

      resources :settings, :only => [:index] do
        get :start
        get :stop
      end
    end

    resources :purchases
    resources :disciplines, :only => [:index] do
      member do
        get :like
        get :confirm
        get :show
      end
    end
    resources :votes do
      member do
        get :confirm
      end
    end

    match 'confirmations/confirm', :to => 'confirmations#confirm', :as => :confirmations

    root :to => 'hello#index'

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  include Stateflow

  WINNERS_LIMIT = 10

  attr_accessible :description, :name, :confirmation_token, :confirmed_at, :state

  has_many :votes

  has_one :photo, :dependent => :destroy

  belongs_to :user

  validates :description, :name, :presence => true

  delegate :name, :email, :to => :user, :prefix => true, :allow_nil => true

  scope :confirmed, lambda { where('confirmed_at is not NULL') }
  scope :pending,   lambda { where(:state => 'pending') }
  scope :approved,  lambda { where(:state => 'approved') }
  scope :rejected,  lambda { where(:state => 'rejected') }
  scope :notnull,   lambda { where('votes_count > 0') }
  scope :winners,   approved.order("votes_count DESC limit #{WINNERS_LIMIT}")

  after_create :generate_token
  after_create :send_confirmation

  stateflow do
    initial :pending

    state :pending, :rejected, :approved

    state :rejected do
      enter :send_rejected_notification!
    end

    state :approved do
      enter :send_approved_notification!
    end

    event :approve! do
      transitions :from => :pending, :to => :approved
    end

    event :reject! do
      transitions :from => :pending, :to => :rejected
    end
  end

  class << self
    def by_tournament_state
      if Settings.first.state == 'started'
        Discipline.approved
      else
        Discipline.winners
      end
    end
  end

  def confirm!
    update_attributes(:confirmed_at => DateTime.now)
  end

  def vote_up(user)
    votes.create(:user => user)
  end

  def send_emails
    DisciplineMailer.winner_email(self).deliver
  end

  private

  def generate_token
    token = Token.generate
    update_attributes(:confirmation_token => token)
  end

  def send_confirmation
    DisciplineMailer.send_confirm(self).deliver
  end

  def send_rejected_notification!
    DisciplineMailer.rejected_email(self).deliver
  end

  def send_approved_notification!
    DisciplineMailer.approved_email(self).deliver
  end



end

app/controllers/admin/disciplines_controller.rb
class Admin::DisciplinesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_user_admin
  before_filter :find_discipline, :except => [:index]

  def index
    @confirmed_disciplines = Discipline.confirmed
    @approved_disciplines = Discipline.approved
  end

  def show
    @votes = @discipline.votes
  end

  def destroy
    @discipline.destroy
    redirect_to :action => :index
  end

  def approve
    @discipline.approve!
    @discipline.save
    redirect_to :action => :index
  end

  def reject
    @discipline.reject!
    @discipline.save
    redirect_to :action => :index
  end

  def winners
    @winners_disciplines = Discipline.approved.winners.notnull
  end

  def send_notification_to_winners
    @winners = Discipline.approved.winners.notnull
    @winners.each do |winner|
      winner.send_emails
    end
    redirect_to :action => :index
  end


  private

  def find_discipline
    @discipline = Discipline.find_by_id(params[:id])
  end
end

app/controllers/disciplines_controller.rb
# encoding: UTF-8
class DisciplinesController < ApplicationController
  before_filter :tournaments_are_enabled, :only => [:like]
  before_filter :find_discipline, :except => [:index]
  before_filter :confirmed_user, :except => [:index,:show]

  def index
    status = Settings.first.state
    if status == 'started'
      @disciplines = Discipline.approved
      render :template => "disciplines/index_approved.xml.builder"
    elsif status == 'stoped'
      @disciplines = Discipline.winners
      render :template => "disciplines/index_winners.xml.builder"
    end
  end

  def confirm
    @discipline.confirm!
    render :text => 'Дисциплина подтверджена'
  end

  def like
    @user = User.find_by_email(params[:email])
    @vote = Vote.unscoped.upcoming(@user.id, params[:id])

    if @vote.count == 0
      @discipline.vote_up(@user)
    end
  end

  def show
    meta_info = MetaTagsSoc.new({ :discipline => @discipline, 
                                  #:soc_type => params[:soc], 
                                  :request => request })
    set_meta_tags(meta_info.generator)
  end

  private

  def find_discipline
    @discipline = Discipline.find_by_id(params[:id])
  end


end

app/helpers/admin/disciplines_helper.rb
module Admin::DisciplinesHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/admin/disciplines/_approved_discipline.html.slim
tr
  td= approved_discipline.id
  td= approved_discipline.user_name
  td= approved_discipline.user_email
  td= approved_discipline.name
  td= approved_discipline.description
  td= approved_discipline.votes_count

app/views/admin/disciplines/_confirmed_discipline.html.slim
tr data-link="#{admin_discipline_path(confirmed_discipline)}"
  td= confirmed_discipline.id
  td= confirmed_discipline.user_name
  td= confirmed_discipline.user_email
  td= confirmed_discipline.name
  td= confirmed_discipline.description
  td
    div
      = link_to t('.approve'), approve_admin_discipline_path(confirmed_discipline), :class => 'approve'
    div
      = link_to t('.reject'), reject_admin_discipline_path(confirmed_discipline), :class => 'reject'
  td= link_to t('.destroy'), admin_discipline_path(confirmed_discipline), :method => 'delete'

app/views/admin/disciplines/_discipline.html.slim
td= confirmed_discipline.id
td= confirmed_discipline.user_name
td= confirmed_discipline.user_email
td= confirmed_discipline.name
td= confirmed_discipline.description
td
  div
    = link_to t('.approve'), admin_discipline_approve_path(confirmed_discipline), :class => 'approve'
  div
    = link_to t('.reject'), admin_discipline_reject_path(confirmed_discipline), :class => 'reject'

app/views/admin/disciplines/_vote.html.slim
tr
  td= vote.id
  td= vote.user_email
  td= link_to t('.destroy'), admin_discipline_vote_path(@discipline, vote), :method => 'delete'

app/views/admin/disciplines/_winner_discipline.html.slim
tr
  td= winner_discipline.id
  td= winner_discipline.user_name
  td= winner_discipline.user_email
  td= winner_discipline.name
  td= winner_discipline.description
  td= winner_discipline.votes_count

  - if winner_discipline.photo
    td= winner_discipline.photo.photo_file_name
    td= link_to t('.destroy'), admin_discipline_photo_path(winner_discipline, winner_discipline.photo.id), :method => 'delete'
  - else
    td = form_for :photo, :url => admin_discipline_photos_path(winner_discipline), :html => { :multipart => true } do |f|
      = f.file_field :photo
      = f.submit t('.add_photo')

app/views/admin/disciplines/index.html.slim
table#disciplines
  tr
    th= t('.id')
    th= t('.user_name')
    th= t('.email')
    th= t('.discipline_name')
    th= t('.description')
    th= t('.actions')
  = render :partial => 'confirmed_discipline', :collection => @confirmed_disciplines

table#disciplines
  tr
    th= t('.id')
    th= t('.user_name')
    th= t('.email')
    th= t('.discipline_name')
    th= t('.description')
    th= t('.votes_count')
  = render :partial => 'approved_discipline', :collection => @approved_disciplines

app/views/admin/disciplines/show.html.slim
h3= @discipline.name
h4= t('.votes')

table#votes
  tr
    th= t('.id')
    th= t('.user_email')
  = render :partial => 'vote', :collection => @votes

app/views/admin/disciplines/winners.html.slim
table#disciplines
  tr
    th= t('.id')
    th= t('.user_name')
    th= t('.email')
    th= t('.discipline_name')
    th= t('.description')
    th= t('.votes_count')
    th= t('.photo')
  = render partial: 'winner_discipline', collection: @winners_disciplines
  
<br>
= link_to "Вислать емейл победителям", send_notification_to_winners_admin_disciplines_path